FROM ubuntu:latest

ARG DEBIAN_FRONTEND=noninteractive
ENV MAVEN_VERSION=3.9.6 \
    JAVA_VERSION=17

RUN apt-get update && \
    apt-get install -y --no-install-recommends \
        wget curl git vim gnupg2 ca-certificates && \
    apt-get install -y build-essential && \
    # JDK
    apt-get install -y --no-install-recommends openjdk-${JAVA_VERSION}-jdk && \
    # Maven
    wget -q https://archive.apache.org/dist/maven/maven-3/${MAVEN_VERSION}/binaries/apache-maven-${MAVEN_VERSION}-bin.tar.gz -O /tmp/maven.tgz && \
    tar xzf /tmp/maven.tgz -C /opt && ln -s /opt/apache-maven-${MAVEN_VERSION}/bin/mvn /usr/local/bin/mvn && \
    rm -rf /var/lib/apt/lists/* /tmp/maven.tgz

WORKDIR /workspace
